- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars: 
      timings: "7:15am"
    ansible.builtin.debug:
      msg: "Hi we are learning {{Course}} from trainer {{Trainer}}, Duration is {{Duration}} and the timings are {{timings}}"