- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

  - name: upper case
    vars:
      greeting: "Hello, Good morning"
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"