- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'docker', state: 'latest'}
    - {name: 'nginx', state: 'absent'}
    - {name: 'mysql', state: 'absent'}